### ISSUE TITLE
Capabilities & Limitations Estimation?

### ISSUE THREAD

**Issue by lonnieOST** [IntelLabs/pmgd#16]
Hello,

Hope that you are doing well.

Although I know that you are currently working on the new version which will be much more advanced, I was wondering if I might be able to get some "rough" estimates from you on the PMGD limitations.

I also did come across a paper "Addressing the Dark Side of Vision Research: Storage" (Vishakha Gupta-Cledat, Luis Remis, Christina R. Strong) which talked briefly about PMGD but did not really go into its capabilities and limitations towards answering my question.

In particular, I am interested in:

1. approximate max nodes/vertices & edges
2. approximate number of transactions per second
3. any information on the stability
4. I think that PMGD is also only single node.

I am considering to use PMGD in a cutting edge project but am trying to get so base estimations on its current capabilities and limitations.

Best Regards :)

**Comment by philiplantz** [comment]
The number of nodes and edges is limited only by the amount of persistent memory available in the platform. By default, nodes are 64 bytes and edges are 32 bytes; this figure includes space for a small number of property values. Additional persistent memory space is needed for additional node and edge properties, the edge lists of nodes, and indices. All persistent memory data structures are designed for compactness (balanced with ease/speed of access).

A PMGD transaction may consist of anything from looking up a single node and retrieving one of its properties to a complex query that searches many nodes for patterns involving neighbors, tags, properties, etc. and calculating some result based on the properties found, which of course results in a very wide range of execution times.

PMGD does not include any multi-node support.

**Comment by lonnieOST** [comment]
Thank you for answering my inquiry about general capabilities of PMGD.

I have a reasonable background in C/C++ and definitely like it over Java for which I have seen most other Graph database solutions.  

While I do understand that PMGD is still in development and may not yet be as mature as other off the shelf solutions, from what I have seen, so far, I think that it offers GREAT potential and it also gives me the opportunity to really dig into the code as well as to allow me to have truly customized solution to fit my project directly.

I am trying to build a simple movie-user rating application, mostly to get acquainted with PMGD and a feel for how things are done along with adding a simple JSON middleware with the Crow library to see how hard it is to put it all together.

If my first applications goes well, then I would like to explore expanding the PMGD "concurrency" version (since it will hand threading better from what I understand given the limited documentation on it) towards an highly distributed self-balancing model using a P2P approach. (future exploration, perhaps)

Most graph databases have some types of limitations in the, say, 100 billion nodes and edges range but it looks like PMGD has much larger capabilities if the platform supported it.

Right now, I am spending a bunch of time in your "tests" folder trying to get an understanding on how to implement just the basic movie-user rating application. 

If there is any type of peer review paper available, as the github README seems to indicate then I would really like to get this paper and read over it to gather more information. Also, any other publications or presentations would be very helpful as well.

PMGD is a very exciting project and I can see working with it in a number of real-world projects in the very near future.

Thanks again and have a great day.

**Comment by vishakha041** [comment]
We would be very interested in understanding your plans and experience with PMGD and answering your questions. You can reach out to my Intel email so we can setup a conversation.  It is in the AUTHORS document.

**Comment by lonnieOST** [comment]
Hi, I will try to work out a simple demo and then reach out to you do discuss more details.

What is the main difference between the:

ConcurrencyWithMSync
and
concurrency-with-msync
and
connurency

Which is the one that I most relevant since there is the "master" pmgd single-thread, I presume and one of the concurrency branches above that are the active development.

Thanks,

**Comment by lonnieOST** [comment]
I forgot to ask when the new release might be coming out with the many updates and fixes that you have been working on?

Also, will there be any new test/example cases? I am reviewing all of what I can find in the repository to try to get a feel for a very simple example that could show me how to basically setup a simple movie ratings example with a couple of users to vote on movies, or something similar and it is mainly for learning so that I can later build a much larger website & product rating system based on ideas learned from a simpler rating demo.

Cheers and have a great day :)
