### ISSUE TITLE
Strange compile error

### ISSUE THREAD

**Issue by lonnieOST** [IntelLabs/pmgd#17]
Hello,

I was previously able to compile PMGD on my Ubuntu 16.04 system. 

Recently, I upgraded to Ubuntu 18.04 and tried to do a fresh compile of PMGD but am now getting some strange errors:

---------------------------------------------
~/VARS/pmgd/test$ make all
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[CC] src/graph.o
[CC] src/GraphConfig.o
[CC] src/node.o
[CC] src/edge.o
[CC] src/StringTable.o
[CC] src/PropertyList.o
[CC] src/property.o
[CC] src/stringid.o
In file included from src/property.cc:31:0:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/edge.h:34:0,
                 from src/edge.cc:31:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
src/Makeconf:35: recipe for target 'src/property.o' failed
make[1]: *** [src/property.o] Error 1
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
[CC] src/TransactionManager.o
In file included from ./include/graph.h:34:0,
                 from ./include/transaction.h:33,
                 from src/TransactionImpl.h:38,
                 from src/StringTable.cc:33:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/graph.h:34:0,
                 from src/GraphConfig.cc:33:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/graph.h:34:0,
                 from src/graph.cc:32:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from src/node.cc:33:0:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
In file included from ./include/graph.h:34:0,
                 from src/PropertyList.cc:36:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/graph.h:34:0,
                 from ./include/transaction.h:33,
                 from src/TransactionImpl.h:38,
                 from src/stringid.cc:34:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
src/Makeconf:35: recipe for target 'src/StringTable.o' failed
make[1]: *** [src/StringTable.o] Error 1
[CC] src/transaction.o
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
In file included from ./include/graph.h:34:0,
                 from ./include/transaction.h:33,
                 from src/TransactionImpl.h:38,
                 from src/TransactionManager.cc:33:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
src/Makeconf:35: recipe for target 'src/edge.o' failed
make[1]: *** [src/edge.o] Error 1
[CC] src/Index.o
src/Makeconf:35: recipe for target 'src/GraphConfig.o' failed
make[1]: *** [src/GraphConfig.o] Error 1
----------------------------------------
There are, of course, many more errors showing up now.

Did I miss something here?
Cheer

**Comment by Ragaad** [comment]
I think you got new gcc version working. I got the same error with gcc6, the sloution in my case was to change the unint8_t_chunk0[] to unint8_t_chunk0[0] in include/iterator.h

Ragaad
________________________________

**Comment by luisremis** [comment]
Fixed in #18, thanks for your comment.

**Comment by lonnieOST** [comment]
Thanks for the fix on this as I later found out that the Ubuntu 18.04 installs GCC 7.3 where as in my older Ubunt 16.04 it was GCC 5.4

There were also a couple of additional warnings that were treated as errors in the base "make"
.
.
.
--------------------------------------
test/propertypredicatetest.cc: In function ‘int main(int, char**)’:
test/propertypredicatetest.cc:40:5: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 5 [-Wformat-overflow=]
 int main(int argc, char **argv)
     ^~~~
test/propertypredicatetest.cc:40:5: note: directive argument in the range [1, 2147483647]
In file included from /usr/include/stdio.h:862:0,
                 from test/propertypredicatetest.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:34:43: note: ‘__builtin___sprintf_chk’ output between 5 and 14 bytes into a destination of size 8
       __bos (__s), __fmt, __va_arg_pack ());
                                           ^
--------------------------------------
and 
---------------------------------------
[CC] test/emailindextest.o
test/filtertest.cc: In function ‘int main(int, char**)’:
test/filtertest.cc:41:5: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 5 [-Wformat-overflow=]
 int main(int argc, char **argv)
     ^~~~
test/filtertest.cc:41:5: note: directive argument in the range [1, 2147483632]
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6352,
                 from /usr/include/c++/7/string:52,
                 from ./include/pmgd.h:34,
                 from test/filtertest.cc:36:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:34:43: note: ‘__builtin___sprintf_chk’ output between 5 and 14 bytes into a destination of size 8
       __bos (__s), __fmt, __va_arg_pack ());
---------------------------------------

Thanks again as I am really liking PMGD more and more.
:)
